export const alertFrequencies = [
  { value: "hourly", label: "Hourly" },
  { value: "every_6h", label: "Every 6 hours" },
  { value: "daily_morning", label: "Daily morning" },
  { value: "daily_evening", label: "Daily evening" }
] as const;

export const locationOptions = [
  "Any",
  "India",
  "Remote",
  "United States",
  "Canada",
  "Singapore",
  "United Kingdom"
] as const;

export const experienceLevels = [
  { value: "any", label: "Any level" },
  { value: "internship", label: "Internship" },
  { value: "entry", label: "Entry level" },
  { value: "mid", label: "Mid level" },
  { value: "senior", label: "Senior" },
  { value: "staff", label: "Staff / Principal" },
  { value: "manager", label: "Manager" }
] as const;

export const softwareKeywordPresets = [
  "Software Engineer",
  "Software Developer",
  "Software Development Engineer",
  "SWE",
  "SDE",
  "Backend",
  "Frontend",
  "Full Stack",
  "Platform",
  "Infrastructure",
  "DevOps",
  "SRE",
  "Site Reliability",
  "Cloud",
  "Distributed Systems",
  "Android",
  "iOS",
  "Mobile",
  "Data Engineer",
  "Data Scientist",
  "Analytics Engineer",
  "Machine Learning",
  "ML Engineer",
  "Applied Scientist",
  "AI",
  "Security Engineer",
  "QA",
  "Automation",
  "Product Engineer",
  "Product Manager",
  "New Grad",
  "Intern"
] as const;

export const companyTagOptions = [
  { value: "all", label: "All" },
  { value: "pollable", label: "Pollable" },
  { value: "faang", label: "FAANG+" },
  { value: "product", label: "Product" },
  { value: "startup", label: "Startups" },
  { value: "fintech", label: "Fintech" },
  { value: "service", label: "WITCH/Service" },
  { value: "india", label: "India" },
  { value: "global", label: "Global" }
] as const;

export const seedCompanies = [
  { name: "Google", slug: "google", tags: ["faang", "product", "global", "india"] },
  { name: "Meta/Facebook", slug: "meta", tags: ["faang", "product", "global", "india"] },
  { name: "Amazon", slug: "amazon", tags: ["faang", "product", "global", "india"] },
  { name: "Apple", slug: "apple", tags: ["faang", "product", "global", "india"] },
  { name: "Netflix", slug: "netflix", tags: ["faang", "product", "global"] },
  { name: "Microsoft", slug: "microsoft", tags: ["faang", "product", "global", "india"] },
  { name: "Adobe", slug: "adobe", tags: ["product", "global", "india"] },
  { name: "PayPal", slug: "paypal", tags: ["fintech", "product", "global", "india"] },
  { name: "Atlassian", slug: "atlassian", tags: ["product", "global", "india"] },
  { name: "Snowflake", slug: "snowflake", tags: ["product", "global", "india"] },
  { name: "Rubrik", slug: "rubrik", tags: ["product", "global", "india"] },
  { name: "Coupang", slug: "coupang", tags: ["product", "global"] },
  { name: "PhonePe", slug: "phonepe", tags: ["fintech", "product", "startup", "india"] },
  { name: "Meesho", slug: "meesho", tags: ["product", "startup", "india"] },
  { name: "Groww", slug: "groww", tags: ["fintech", "product", "startup", "india"] },
  { name: "CRED", slug: "cred", tags: ["fintech", "product", "startup", "india"] },
  { name: "Razorpay", slug: "razorpay", tags: ["fintech", "product", "startup", "india"] },
  { name: "Paytm", slug: "paytm", tags: ["fintech", "product", "india"] },
  { name: "Slice", slug: "slice", tags: ["fintech", "product", "startup", "india"] },
  { name: "Zerodha", slug: "zerodha", tags: ["fintech", "product", "india"] },
  { name: "Navi", slug: "navi", tags: ["fintech", "product", "startup", "india"] },
  { name: "Flipkart", slug: "flipkart", tags: ["product", "india"] },
  { name: "Swiggy", slug: "swiggy", tags: ["product", "startup", "india"] },
  { name: "Zomato", slug: "zomato", tags: ["product", "startup", "india"] },
  { name: "Dream11", slug: "dream11", tags: ["product", "startup", "india"] },
  { name: "Ola", slug: "ola", tags: ["product", "startup", "india"] },
  { name: "Urban Company", slug: "urbancompany", tags: ["product", "startup", "india"] },
  { name: "MakeMyTrip", slug: "makemytrip", tags: ["product", "india"] },
  { name: "Freshworks", slug: "freshworks", tags: ["product", "global", "india"] },
  { name: "Zoho", slug: "zoho", tags: ["product", "global", "india"] },
  { name: "InMobi", slug: "inmobi", tags: ["product", "global", "india"] },
  { name: "Postman", slug: "postman", tags: ["product", "global", "india"] },
  { name: "BrowserStack", slug: "browserstack", tags: ["product", "global", "india"] },
  { name: "Whatfix", slug: "whatfix", tags: ["product", "startup", "global", "india"] },
  { name: "Chargebee", slug: "chargebee", tags: ["product", "startup", "global", "india"] },
  { name: "Atlan", slug: "atlan", tags: ["product", "startup", "global", "india"] },
  { name: "CleverTap", slug: "clevertap", tags: ["product", "startup", "global", "india"] },
  { name: "ShareChat", slug: "sharechat", tags: ["product", "startup", "india"] },
  { name: "Udaan", slug: "udaan", tags: ["product", "startup", "india"] },
  { name: "Tekion", slug: "tekion", tags: ["product", "startup", "global", "india"] },
  { name: "Turing", slug: "turing", tags: ["product", "startup", "global"] },
  { name: "Quince", slug: "quince", tags: ["product", "startup", "global"] },
  { name: "Uber", slug: "uber", tags: ["product", "global", "india"] },
  { name: "Airbnb", slug: "airbnb", tags: ["product", "global", "india"] },
  { name: "Stripe", slug: "stripe", tags: ["fintech", "product", "global", "india"] },
  { name: "Databricks", slug: "databricks", tags: ["product", "global", "india"] },
  { name: "Coinbase", slug: "coinbase", tags: ["fintech", "product", "global", "india"] },
  { name: "MongoDB", slug: "mongodb", tags: ["product", "global", "india"] },
  { name: "Okta", slug: "okta", tags: ["product", "global", "india"] },
  { name: "Twilio", slug: "twilio", tags: ["product", "global", "india"] },
  { name: "Asana", slug: "asana", tags: ["product", "global"] },
  { name: "Figma", slug: "figma", tags: ["product", "global"] },
  { name: "Canva", slug: "canva", tags: ["product", "global", "india"] },
  { name: "NVIDIA", slug: "nvidia", tags: ["product", "global", "india"] },
  { name: "AMD", slug: "amd", tags: ["product", "global", "india"] },
  { name: "Oracle", slug: "oracle", tags: ["product", "global", "india"] },
  { name: "SAP", slug: "sap", tags: ["product", "global", "india"] },
  { name: "Intuit", slug: "intuit", tags: ["fintech", "product", "global", "india"] },
  { name: "Salesforce", slug: "salesforce", tags: ["product", "global", "india"] },
  { name: "ServiceNow", slug: "servicenow", tags: ["product", "global", "india"] },
  { name: "Walmart Global Tech", slug: "walmart", tags: ["product", "global", "india"] },
  { name: "JPMorgan Chase", slug: "jpmorgan", tags: ["fintech", "product", "global", "india"] },
  { name: "Goldman Sachs", slug: "goldmansachs", tags: ["fintech", "product", "global", "india"] },
  { name: "Morgan Stanley", slug: "morganstanley", tags: ["fintech", "product", "global", "india"] },
  { name: "TCS", slug: "tcs", tags: ["service", "india"] },
  { name: "Infosys", slug: "infosys", tags: ["service", "india"] },
  { name: "Wipro", slug: "wipro", tags: ["service", "india"] },
  { name: "HCLTech", slug: "hcltech", tags: ["service", "india"] },
  { name: "Tech Mahindra", slug: "techmahindra", tags: ["service", "india"] },
  { name: "Cognizant", slug: "cognizant", tags: ["service", "global", "india"] },
  { name: "Accenture", slug: "accenture", tags: ["service", "global", "india"] },
  { name: "Capgemini", slug: "capgemini", tags: ["service", "global", "india"] }
] as const;
